# fly.toml app configuration file generated for azohome on 2023-07-08T17:55:52-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "azohome"
primary_region = "ams"
console_command = "/rails/bin/rails console"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[env]
  RAILS_STORAGE = "/data/storage"